### PR TITLE
Fix compilation error when toolchain supports sse3, sse4

### PR DESCRIPTION
**Pull request by lzy1g1225**
Fix the compilation error:
"error: always_inline function '_mm_shuffle_epi8' requires target feature 'ssse3', but would be inlined into function 'RotateLeft32' that is compiled without support for 'ssse3' ... "

### CODE REVIEW

**Comment by noloader** [comment]
It sounds like you should be using [cryptopp-cmake-8.2.0](https://github.com/noloader/cryptopp-cmake/releases/tag/CRYPTOPP_8_2_0).

cryptopp-autotools and cryptopp-cmake follows Crypto++ releases. They are also sync'd with Crypto++ master. Crypto++ master removed the 64-bit SIMD implementations.

The SIMD files for 64-bit block ciphers were removed because they failed to produce correct results in some modes. Also see [Issue 945](https://github.com/weidai11/cryptopp/issues/945).

**Comment by lzy1g1225** [comment]
Thanks, I was using both cryptopp master and cryptopp-cmake master. Switch both repo to tag 8.2 works now.

**Comment by noloader** [comment]
@lzy1g1225,

> Thanks, I don't know about cryptopp, but I was actually using both cryptopp-master and cryptopp-cmake-master.

Something does not sound correct for you here.

Here's what my Master looks like. Notice there is no `simeck_simd.cpp`, `simon64_simd.cpp` or `speck64_sid.cpp`.

```
cryptopp$ ls *_simd.cpp
aria_simd.cpp     crc_simd.cpp     neon_simd.cpp      simon128_simd.cpp
blake2b_simd.cpp  gcm_simd.cpp     ppc_simd.cpp       sm4_simd.cpp
blake2s_simd.cpp  gf2n_simd.cpp    rijndael_simd.cpp  speck128_simd.cpp
chacha_simd.cpp   keccak_simd.cpp  shacal2_simd.cpp   sse_simd.cpp
cham_simd.cpp     lea_simd.cpp     sha_simd.cpp
```

And here is the result of cryptopp-cmake master. Again, no `simeck_simd.cpp`, `simon64_simd.cpp` or `speck64_sid.cpp`.

```
cryptopp-cmake$ grep -E 'simeck_simd|simon64_simd|speck64_simd' CMakeLists.txt 
cryptopp-cmake$
```

**Comment by lzy1g1225** [comment]
Looks like my local copy are not same as the remote. Sorry for that!

**Pull request closed without merging**
